# Generated by Django 2.2.6 on 2020-12-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
